services:
  php-fpm:
    image: ${PHP_IMAGE_NAME}
    build:
      context: ./dockerfiles/php-fpm
    env_file:
      - .env
    ports:
      - "22:22"
      - "990:990"
    secrets:
      - host_ssh_key
    volumes:
      - rootcert:/etc/ssl/warden-rootca-cert
      - composer:/home/www-data/.composer
      - ./.warden/conf/01-php.ini:/etc/php.d/01-php.ini
      - .env:/var/www/.env
      - ~/.ssh:/root/.ssh-keys:ro
    environment:
      SSH_USER: $USER

  db:
    volumes:
      - "./data/db/mysql:/var/lib/mysql"

  elasticsearch:
    hostname: "${WARDEN_ENV_NAME}-elasticsearch"
    image: ${WARDEN_IMAGE_REPOSITORY}/elasticsearch:${ELASTICSEARCH_VERSION:-8.11}
    labels:
      - traefik.enable=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-elasticsearch.tls=true
      - traefik.http.routers.${WARDEN_ENV_NAME}-elasticsearch.rule=Host(`elasticsearch.${TRAEFIK_DOMAIN}`)
      - traefik.http.services.${WARDEN_ENV_NAME}-elasticsearch.loadbalancer.server.port=9200
      - traefik.docker.network=${WARDEN_ENV_NAME}_default
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms16g -Xmx16g"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  rootcert: {}
  composer: {}
  esdata:

secrets:
  host_ssh_key:
    file: ~/.ssh/id_rsa
